"""Generate the human-readable meeting_report.md."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np


def _load_json(path: Path) -> Optional[Dict[str, Any]]:
    if path.exists():
        return json.loads(path.read_text())
    return None


def _load_all_qc(qc_dir: Path, sites: List[str]) -> Dict[str, List[Dict[str, Any]]]:
    result: Dict[str, List[Dict[str, Any]]] = {}
    for site in sites:
        site_dir = qc_dir / site
        records = []
        if site_dir.exists():
            for f in sorted(site_dir.glob("*_qc.json")):
                records.append(json.loads(f.read_text()))
        result[site] = records
    return result


def _load_al_queue(site_reports_dir: Path) -> List[Dict[str, Any]]:
    path = site_reports_dir / "active_learning_queue.json"
    if path.exists():
        return json.loads(path.read_text())
    return []


def _load_fl_rounds(fl_dir: Path) -> List[Dict[str, Any]]:
    rounds = []
    for f in sorted(fl_dir.glob("round_*_summary.json")):
        rounds.append(json.loads(f.read_text()))
    return rounds


def generate_meeting_report(
    data_root: Path, outputs_root: Path, config: Dict[str, Any]
) -> Path:
    sites: List[str] = config.get("sites", ["site_A", "site_B", "site_C"])
    qc_dir = outputs_root / "qc_reports"
    al_dir = outputs_root / "site_reports"
    fl_dir = outputs_root / "fl_rounds"

    all_qc = _load_all_qc(qc_dir, sites)
    al_queue = _load_al_queue(al_dir)
    fl_rounds = _load_fl_rounds(fl_dir)

    lines: List[str] = []

    lines += [
        "# Agentic Federated Labeling Infrastructure for Trustworthy Prostate MRI AI",
        "",
        "> **Note:** This is a demo report generated from synthetic data only.",
        "> It is not a clinical report and contains no real patient information.",
        "",
        "---",
        "",
        "## Research Question",
        "",
        "Can we design a privacy-preserving, multi-site, AI-assisted labeling infrastructure",
        "for prostate MRI that supports federated learning, audit transparency, and",
        "active-learning-guided human QC — without sharing raw imaging data?",
        "",
        "---",
        "",
        "## Workflow Summary",
        "",
        "```",
        "Site A ──┐                                    ┌── Site A (stays local)",
        "Site B ──┤── AutoLabel + QC + Active Learning ─┤── Site B (stays local)",
        "Site C ──┘                                    └── Site C (stays local)",
        "              │                                         │",
        "              ▼                                         ▼",
        "       FL Coordinator                           Human Reviewer",
        "  (model deltas + QC stats only)           (prioritised review queue)",
        "```",
        "",
        "**Privacy invariant:** Image data never leave the originating site.",
        "",
        "---",
        "",
        "## Per-Site Data Profile",
        "",
    ]

    for site in sites:
        recs = all_qc.get(site, [])
        n = len(recs)
        if n == 0:
            lines.append(f"### {site}\n\nNo data found.\n")
            continue
        n_pass = sum(1 for r in recs if r["status"] == "auto_qc_pass")
        n_review = sum(1 for r in recs if r["status"] == "review_required")
        n_reject = sum(1 for r in recs if r["status"] == "reject_or_redraw")
        dice_vals = [r["dice_vs_gt"] for r in recs if r.get("dice_vs_gt") is not None]
        mean_dice = f"{np.mean(dice_vals):.3f}" if dice_vals else "N/A"
        shift = recs[0].get("site_shift_risk", "?")
        lines += [
            f"### {site}",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total cases | {n} |",
            f"| QC pass | {n_pass} ({n_pass/n:.0%}) |",
            f"| Review required | {n_review} ({n_review/n:.0%}) |",
            f"| Reject / redraw | {n_reject} ({n_reject/n:.0%}) |",
            f"| Mean Dice (vs GT) | {mean_dice} |",
            f"| Site shift risk | {shift} |",
            "",
        ]

    lines += [
        "---",
        "",
        "## Auto-Labeling Summary",
        "",
        "Auto-labels were generated by **HeuristicAutoLabeler v0.1.0** (degraded GT masks + morphological noise).",
        "In production, replace with: MONAI Label, nnU-Net, MedSAM, or MedSAM2.",
        "",
        "| Site | Mean Dice | Min Confidence |",
        "|------|-----------|----------------|",
    ]
    for site in sites:
        recs = all_qc.get(site, [])
        dice_vals = [r["dice_vs_gt"] for r in recs if r.get("dice_vs_gt") is not None]
        mean_dice = f"{np.mean(dice_vals):.3f}" if dice_vals else "N/A"
        lines.append(f"| {site} | {mean_dice} | — |")

    lines += [
        "",
        "---",
        "",
        "## QC Summary",
        "",
        "QC features computed per case: prostate volume, connected components, boundary uncertainty,",
        "lesion-inside-prostate check, volume plausibility, site shift risk.",
        "",
        "**Risk flag frequency across all sites:**",
        "",
    ]
    all_flags: Dict[str, int] = {}
    for recs in all_qc.values():
        for r in recs:
            for flag in r.get("risk_flags", []):
                all_flags[flag] = all_flags.get(flag, 0) + 1
    if all_flags:
        lines.append("| Flag | Count |")
        lines.append("|------|-------|")
        for flag, cnt in sorted(all_flags.items(), key=lambda x: -x[1]):
            lines.append(f"| `{flag}` | {cnt} |")
    else:
        lines.append("No risk flags recorded.")

    lines += [
        "",
        "---",
        "",
        "## Active Learning Review Queue",
        "",
        "Top 10 cases prioritised for human review (descending priority score):",
        "",
        "| Rank | Case ID | Site | Priority Score | Reasons |",
        "|------|---------|------|----------------|---------|",
    ]
    for entry in al_queue[:10]:
        reasons = "; ".join(entry.get("reasons", []))[:80] or "—"
        lines.append(
            f"| {entry['rank']} | {entry['case_id']} | {entry['site_id']} "
            f"| {entry['priority_score']:.4f} | {reasons} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Federated Learning Simulation",
        "",
        f"**{len(fl_rounds)} FL rounds simulated.**",
        "",
        "| Round | Global Confidence | Review Rate | Notes |",
        "|-------|------------------|-------------|-------|",
    ]
    for rnd in fl_rounds:
        lines.append(
            f"| {rnd['round_number']} "
            f"| {rnd['global_mean_confidence']:.3f} "
            f"| {rnd['global_review_rate']:.2f} "
            f"| {rnd['notes'][:60]}… |"
        )

    lines += [
        "",
        "---",
        "",
        "## Privacy and Audit Statement",
        "",
        "- Raw MRI volumes remained on their originating site at all times.",
        "- Only the following were transmitted to the FL coordinator:",
        "  - Model weight delta norms (scalar values, no weights).",
        "  - Aggregated QC statistics (pass rate, review rate, mean Dice).",
        "  - Case counts (processed / needing review).",
        "- Audit JSON files are written to `outputs/site_reports/<site>_audit.json`",
        "  and `outputs/fl_rounds/` for full traceability.",
        "- In production, differential privacy (Gaussian mechanism) should be applied",
        "  to gradient updates before transmission.",
        "",
        "---",
        "",
        "## Next Steps for Real Deployment",
        "",
        "| Component | Current (MVP) | Production Replacement |",
        "|-----------|--------------|------------------------|",
        "| Data | Synthetic NumPy volumes | Hospital DICOM/NIfTI via MONAI or SimpleITK |",
        "| Auto-labeler | Heuristic GT degradation | MONAI Label, nnU-Net, MedSAM, MedSAM2 |",
        "| FL framework | Simulated summaries | Flower (flwr) or NVFLARE |",
        "| QC metrics | Heuristic thresholds | Radiologist correction + inter-reader studies |",
        "| Privacy | None (demo) | Differential privacy, secure aggregation |",
        "| Audit | JSON files | Immutable audit log (e.g., FHIR AuditEvent, blockchain) |",
        "",
        "---",
        "",
        "*Generated automatically by the Agentic Federated Labeling demo pipeline.*",
    ]

    report_path = outputs_root / "meeting_report.md"
    report_path.write_text("\n".join(lines) + "\n")
    print(f"  Meeting report written to {report_path}")
    return report_path
